### ISSUE TITLE
Error build on Dev mode: Cannot find module '@babel/plugin-proposal-optional-chaining'

### ISSUE THREAD

**Issue by yossularko** [luicfrr/react-native-vision-camera-face-detector#136]
![Image](https://github.com/user-attachments/assets/feb10bd6-b638-4028-8b1e-fd3422355e80)

Error on RN 0.77.x and RN 0.78.0 but work perfectly on RN 0.76.x

Cannot find module '@babel/plugin-proposal-optional-chaining'

Require stack:
- D:\ReactNative\_rn77\AwesomeProject\node_modules\@babel\core\lib\config\files\plugins.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\@babel\core\lib\config\files\index.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\@babel\core\lib\index.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\metro-transform-worker\src\index.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\metro\src\DeltaBundler\Worker.flow.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\metro\src\DeltaBundler\Worker.js
- D:\ReactNative\_rn77\AwesomeProject\node_modules\jest-worker\build\workers\processChild.js
- Did you mean "@babel/plugin-transform-optional-chaining"?

Make sure that all the Babel plugins and presets you are using
are defined as dependencies or devDependencies in your package.json
file. It's possible that the missing plugin is loaded by a preset
you are using that forgot to add the plugin to its dependencies: you
can workaround this problem by explicitly adding the missing package
to your top-level package.json.

**`package.json` file:**
{
   "dependencies": {
     "react-native": "0.77.1",
     "react-native-vision-camera": "^4.6.4",
     "react-native-vision-camera-face-detector": "^1.8.1",
     "react-native-worklets-core": "^1.5.0"
  }
}

**Comment by yossularko** [comment]
sorry, it's from "react-native-vision-camera": "^4.6.4"
