### ISSUE TITLE
🐛 [Android] compileDebugKotlin fails with vision-camera 5.0.10 - currentResolution not implemented

### ISSUE THREAD

**Issue by ghxstloner** [luicfrr/react-native-vision-camera-face-detector#230]
### What's happening?

After updating react-native-vision-camera to 5.0.10, the Android build fails 
with a Kotlin compilation error. The build worked fine on 5.0.9.

vision-camera 5.0.10 introduced `currentResolution` as an abstract property 
in the CameraOutput base class (PR #3865), but HybridFaceDetectorOutput does 
not implement it, causing the build to fail.

### Reproduceable Code

```tsx
<Camera
  style={StyleSheet.absoluteFill}
  device={device}
  performanceMode="fast"
  runClassifications
  onFacesDetected={handleFacesDetected}
/>
```

### Relevant log output

```shell
e: file:///...node_modules/react-native-vision-camera-face-detector/android/src/main/java/com/margelo/nitro/camera/facedetector/HybridFaceDetectorOutput.kt:23:1 
Class 'HybridFaceDetectorOutput' is not abstract and does not implement abstract base class member:
val currentResolution: Size?

Execution failed for task ':react-native-vision-camera-face-detector:compileDebugKotlin'.
```

### Device

Poco X3 PRO (compilation error, not runtime)

### VisionCamera Version

5.0.10

### VisionCameraFaceDetector Version

2.0.0-2

### Can you reproduce this issue in the VisionCameraFaceDetector Example app?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [x] I am using Expo
- [x] I have searched this in [VisionCamera's Documentation](https://visioncamera.margelo.com/docs)
- [x] I have read all the [VisionCameraFaceDetector's README file](https://github.com/luicfrr/react-native-vision-camera-face-detector)
- [x] I searched for [similar issues in this repository](https://github.com/luicfrr/react-native-vision-camera-face-detector/issues) and found none.
- [x] I understand this is an open-source project and that I am not paying anything to use this package, so I do not expect an urgent fix, a custom feature, or a tutorial on how to do something.
