### ISSUE TITLE
[BUG 🐛] `cannot find type 'Orientation' in scope` Error on version 1.8.X

### ISSUE THREAD

**Issue by nistelb** [luicfrr/react-native-vision-camera-face-detector#135]
**Describe the bug:**
Build is failing while creating a development build on expo, but normal build works fine. I have attached the build log to this issue below.

**Minimum reproducible example:**

Steps to reproduce the behavior. E.g: 
1. Create an expo account
2. Install version 1.8.1 of the react-native-vision-camera-face-detector in an expo v51 project.
3. Run eas init and setup the project using eas.
4. Create/add this to your eas.json file
```
{
  "cli": {
    "version": ">= 0.52.0",
    "appVersionSource": "remote",
    "requireCommit": true
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
      },
      "channel": "development"
    },
}
}
```
4. Create a development build by running: eas build -p ios --profile development

**Expected behavior:**
The expo development build should complete and succeed.

**I have tryed:**
Downgrading the version of the package, and the development client build was successful.

**Logs and Screenshots**
```
  (node_modules/react-native-vision-camera-face-detector/ios/VisionCameraFaceDetectorOrientation.swift:12:20)

  10 |   
  11 |   // The orientation of the physical device's gyro sensor/accelerometer
> 12 |   var orientation: Orientation {
     |                    ^ cannot find type 'Orientation' in scope
  13 |     didSet {
  14 |       if oldValue != orientation {
  15 |         print("Device Orientation changed from \(oldValue) -> \(orientation)")

❌  (node_modules/react-native-vision-camera-face-detector/ios/VisionCameraFaceDetectorOrientation.swift:56:26)

  54 |    Get the current device orientation from the given acceleration/gyro data.
  55 |    */
> 56 |   var deviceOrientation: Orientation {
     |                          ^ cannot find type 'Orientation' in scope
```

**Device:**
 - Device: IOS development Build
 - OS: IOS

**`package.json` file:**
{
   "dependencies": {
"expo": "51.X.X",
   "react-native-vision-camera": "4.5.2",
"react-native-vision-camera-face-detector": "1.8.1",
"react-native-worklets-core": "^1.3.3",
  }
}

**Comment by luicfrr** [comment]
I can't reproduce this error on my setup but I'm not using eas online build (not using eas at all on example app neither online build on my real app) so maybe this is the point...

**Comment by rfariasrzx** [comment]
Hey guys, 

I'm having the same problem.

Expo developer build not working with 1.8.1

I've tried with 1.7.1 and it worked.

Now I will try with 1.7.2 and 1.8.0 

I think that 1.8.0 will not work because was in this version that the Orientation  was modified.

**Comment by NicolasHubner** [comment]
I was having this problem to build on IOs, and I put this version to work with me.

  "expo": "~51.0.39",
    "react-native-vision-camera": "^4.6.3",
    "react-native-vision-camera-face-detector": "^1.8.1",
  "react-native-worklets-core": "1.3.3",

**Comment by jesulonimii** [comment]
That's interesting.
I will try your configuration and revert

**Comment by moa-torres** [comment]
> I was having this problem to build on IOs, and I put this version to work with me.
> 
> "expo": "~51.0.39", "react-native-vision-camera": "^4.6.3", "react-native-vision-camera-face-detector": "^1.8.1", "react-native-worklets-core": "1.3.3",

worked on expo 50 too

**Comment by luicfrr** [comment]
Now I've noticed that you're not using a tested vision-camera version so I'm closing this issue as invalid.

> **`package.json` file:** { "dependencies": { "expo": "51.X.X", "react-native-vision-camera": "4.5.2", "react-native-vision-camera-face-detector": "1.8.1", "react-native-worklets-core": "^1.3.3", } }


As it seems, using correct tested versions "solves" the problem
> I was having this problem to build on IOs, and I put this version to work with me.
> 
> "expo": "~51.0.39", "react-native-vision-camera": "^4.6.3", "react-native-vision-camera-face-detector": "^1.8.1", "react-native-worklets-core": "1.3.3",
